// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHDowkKqEdElFJa5kwcSa3Ct8-J_qCFcs',
    appId: '1:321470759983:web:82880ae984cdb205d1f2da',
    messagingSenderId: '321470759983',
    projectId: 'stock-envanter',
    authDomain: 'stock-envanter.firebaseapp.com',
    storageBucket: 'stock-envanter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-IJmUN85GChA8emrdchwrytb5ca6_VAM',
    appId: '1:321470759983:android:7fb620294ce86e16d1f2da',
    messagingSenderId: '321470759983',
    projectId: 'stock-envanter',
    storageBucket: 'stock-envanter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbZqtI9EZ0eXr3sQjjNfA4HKG46gl5xyA',
    appId: '1:321470759983:ios:feca74000d03a5cad1f2da',
    messagingSenderId: '321470759983',
    projectId: 'stock-envanter',
    storageBucket: 'stock-envanter.appspot.com',
    iosClientId: '321470759983-80k40em95gos127vbeior4p1lumgnu4h.apps.googleusercontent.com',
    iosBundleId: 'com.example.plc2App',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbZqtI9EZ0eXr3sQjjNfA4HKG46gl5xyA',
    appId: '1:321470759983:ios:0d7781eb6c5bd982d1f2da',
    messagingSenderId: '321470759983',
    projectId: 'stock-envanter',
    storageBucket: 'stock-envanter.appspot.com',
    iosClientId: '321470759983-i60gt3m3m6io0khor8oat0mtsoqn675g.apps.googleusercontent.com',
    iosBundleId: 'com.example.plc2App.RunnerTests',
  );
}
